development:
  dialect: postgres
  database: vigilate
  user: postgres
  password: 1234
  host: localhost
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:1234@localhost:5432/vigilate"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_production"}}